### ISSUE TITLE
Module doesn't work

### ISSUE THREAD

**Issue by mattinmelbourne** [TraGicCode/tragiccode-wsusserver#32]
On a new server 2016 and a 2019 install, this just fails to work.

  class { 'wsusserver':
      package_ensure                            => 'present',
      include_management_console                => true,
      service_manage                            => true,
      service_ensure                            => 'running',
      service_enable                            => true,
      wsus_directory                            => 'D:/WSUS',
      join_improvement_program                  => false,
      sync_from_microsoft_update                => true,
      update_languages                          => ['en'],
      products                                  => [
        'Windows Server 2016'
      ],
      update_classifications                    => [
          'Windows Server 2016'
      ],
      targeting_mode                            => 'Client',
      host_binaries_on_microsoft_update         => false,
      synchronize_automatically                 => true,
      synchronize_time_of_day                   => '04:00:00', # 3AM ( UTC ) 24H Clock
      number_of_synchronizations_per_day        => 4,
      trigger_full_synchronization_post_install => true,
  }

Wouldn't you also be specifying the values for update_classifications as security, Critical Updates?
![Puppet Failure](https://user-images.githubusercontent.com/26353158/62500607-b2d5bd00-b82a-11e9-8edd-3a283e0c0c7a.PNG)

**Comment by TraGicCode** [comment]
Hey,

Are you able to run puppet with debug logging and then strip out all the sensitive data? If you can’t do that can u at least get me the logs for the run with the logging level set to verbose?

**Comment by mattinmelbourne** [comment]
[puppetlog.txt](https://github.com/TraGicCode/tragiccode-wsusserver/files/3469715/puppetlog.txt)

hopefully this can provide some further detail

**Comment by TsekNet** [comment]
Seeing the same issues here. FWIW, this seems to be a IIS issue. Here's the actual WSUS error encountered:

```powershell
2019-08-13 22:54:20  Found principal
2019-08-13 22:54:20  Found account
2019-08-13 22:54:20  Got binary SID
2019-08-13 22:54:20  Setting content location...
2019-08-13 22:54:20  Fetching ContentDir from registry store
2019-08-13 22:54:20  Value is S:\WSUS
2019-08-13 22:54:20  Swtching DB to multi-user mode......
2019-08-13 22:54:21  Finished setting multi-user mode
2019-08-13 22:54:21  Writing DB settings to registry...
2019-08-13 22:54:21  Disposing Connection
2019-08-13 22:54:21  Clearing Connection Pools
2019-08-13 22:54:21  Marking PostInstall done for UpdateServices-WidDatabase in the registry...
2019-08-13 22:54:21  Starting service W3SVC
2019-08-13 22:54:21  Configuring IIS...
2019-08-13 22:54:21  Start: ConfigureWebsite
2019-08-13 22:54:22  System.Runtime.InteropServices.COMException (0x80070003): The system cannot find the path specified.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at Microsoft.UpdateServices.Administration.UseCustomWebSite..ctor()
   at Microsoft.UpdateServices.Administration.PostInstall.ConfigureWebsite(Int32 portNumber)
   at Microsoft.UpdateServices.Administration.PostInstall.Run()
   at Microsoft.UpdateServices.Administration.PostInstall.Execute(String[] arguments)
```

**Comment by kreeuwijk** [comment]
It seems this reliant on WSUS needing a default website in IIS that has to have an ID of 1.

- https://nathondalton.wordpress.com/2018/03/17/wsus-post-install-failure/
- https://social.technet.microsoft.com/Forums/en-US/512abca3-c1d5-4a18-a22e-90a4c9476476/wsus-postconfiguration-fails-after-an-upgrade-to-2012-r2?forum=winserverwsus
- http://eddiejackson.net/wp/?p=14382

**Comment by TsekNet** [comment]
Setting the IIS website to have an ID of 1 seems to have fixed it.

It looks like the postinstall commands are not functioning correctly. Not sure if related. Have to run them manually after installing the server role.

**Comment by mattinmelbourne** [comment]
Also, in a previous install I was seeing errors when trying to install this on a core server without any gui installed.
Even after setting include_management_console => false , it still fails.
as I'm most sure most place would want this installed in a core setup, is this possible?

**Comment by TraGicCode** [comment]
Closing this issue for now.
