### ISSUE TITLE
Unknown error in config.pp (products)

### ISSUE THREAD

**Issue by odric88** [TraGicCode/tragiccode-wsusserver#39]
Hello,
When i run the module without making a lot of changes, here is the error that appears :
```
`Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: Unhandled exception caught:
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: At line:24 char:21
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: + ...             $currentEnabledProductFamilies = ($wsusServerSubscription ...
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: System.Management.Automation.PropertyNotFoundException: The property 'Title' cannot be found on this object. Verify
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless: that the property exists.
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless:    at CallSite.Target(Closure , CallSite , Object )
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
Debug: /Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/unless:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Debug: STDERR: The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
At line:1 char:5
+ if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
+     ~~~~~~~~~~~~~
Error: 'function Invoke-WsusCategoryConfig {`
```

After the whole function is displayed with the parameters (I attach the txt bellow).
The options are well set but the other modules don't launch because of this error.

[error.txt](https://github.com/TraGicCode/tragiccode-wsusserver/files/4826096/error.txt)
My PP File : [install.txt](https://github.com/TraGicCode/tragiccode-wsusserver/files/4826175/install.txt)

Thanks in advance.

**Comment by TraGicCode** [comment]
Hey @odric88 ,

Is this something you can take a stab at?

**Comment by TraGicCode** [comment]
Hey ,

Someone pointed out I haven’t cut a release which is missing some changes that are in master.  I’ll post back here once I cut a new release and you can see if your issue is resolved

**Comment by odric88** [comment]
Hey,
Okay, thanks for the information.
I'll try again when it's done.

**Comment by TraGicCode** [comment]
Hey,

Can yo go try with the 1.1.3 version uploaded to the forge?

**Comment by odric88** [comment]
Sorry, I left my company and I don't know who took over this project.
